In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
cd drive/MyDrive/zeroday/zeroday/CODE/

/content/drive/MyDrive/zeroday/zeroday/CODE


In [ ]:
import pandas as pd
import numpy as np
from sklearn.svm import OneClassSVM
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import classification_report, accuracy_score
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.svm import OneClassSVM
from sklearn.metrics import classification_report
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout, Input
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
from sklearn.model_selection import train_test_split

In [ ]:
ls

 10-fold-OC-SVM-NSL-KDD.ipynb      'Copy of CICIDS2017_Friday.ipynb'
 1_oneclass_svm_NSLKDD.ipynb       'Copy of CICIDS2017_ZeroDay_IDS.ipynb'
 20n_kmean.json                     DataFiles/
 21n_kmean.json                     Isolation_Forest_Results.docx
 22n_kmean.json                     KDDTest+.txt
 23n_kmean.json                     KDDTrain+.txt
 25-04-25-CICIDS2017_Friday.ipynb   kmean1.weights.h5
 2_CNN__OCSVM_NSLKDD.ipynb          kmean2.weights.h5
 3-Fuzzy-Oneclass-SVM.ipynb         kmean7.keras
 5-4-2025_CICIDS2017.ipynb          kmean9.weights.h5
 Autoencoder+OCSVM.ipynb            kmean.keras
 CICIDS2017_Friday_Balanced.csv     kmean.weights.h5
 CICIDS2017_Friday.ipynb            model_plot_CNN.pdf
 cicids2017.keras                   model_plot_CNN.png
 CICIDS2017_THURDAY.ipynb           model_plot_CNN.svg
 CICIDS2017_Thursday_Balanced.csv   OCSVM_Full_Results_cnn+ocsvm.docx
 cicids2017.weights.h5              OCSVM_Full_Results.docx
 cnnids1.json                       un

In [ ]:
#.....................................OC_SVM.....................

In [ ]:
import pandas as pd
import numpy as np
from sklearn.svm import OneClassSVM
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix

# Step 1: Load CIC-IDS2017 dataset
df = pd.read_csv('CIC-IDS2017/Monday-WorkingHours-Normal-network-activities.csv')
df = pd.read_csv('CIC-IDS2017/Friday-WorkingHours-Afternoon-PortScan.csv')
df = pd.read_csv('CIC-IDS2017/Friday-WorkingHours-Morning-Botnet.csv')
df = pd.read_csv('CIC-IDS2017/Friday-WorkingHours-Afternoon 2-DDoS.csv')

In [ ]:
# Optional: Clean column names (strip spaces)
df.columns = df.columns.str.strip()

# Step 2: Separate features and labels
X = df.drop(['Label'], axis=1)
y = df['Label']

In [ ]:
# Step 3: Encode labels: BENIGN -> 1 (normal), Attack -> -1 (anomaly)
y = y.apply(lambda x: 1 if x == 'BENIGN' else -1)

# Step 4: Handle non-numeric columns (if any)
X = X.select_dtypes(include=[np.number])  # Keep only numeric features

In [ ]:
# Step 5.1: Replace inf and -inf with NaN
X.replace([np.inf, -np.inf], np.nan, inplace=True)

# Step 5.2: Fill NaN with 0 or mean (optional: you can also drop rows)
X.fillna(0, inplace=True)

# Step 6: Normalize
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
# Step 7: Train OCSVM on only benign data
X_train = X_scaled[y == 1]  # Train only on normal traffic
model = OneClassSVM(kernel='sigmoid', gamma='auto', nu=0.1)
model.fit(X_train)

In [ ]:
# Step 8: Predict on full data (benign + attack)
y_pred = model.predict(X_scaled)

# Step 9: Evaluate performance
print("Confusion Matrix:")
print(confusion_matrix(y, y_pred))

print("\nClassification Report:")
print(classification_report(y, y_pred, target_names=['Attack (-1)', 'Benign (1)']))

Confusion Matrix:
[[127333    204]
 [ 12752 114785]]

Classification Report:
              precision    recall  f1-score   support

 Attack (-1)       0.91      1.00      0.95    127537
  Benign (1)       1.00      0.90      0.95    127537

    accuracy                           0.95    255074
   macro avg       0.95      0.95      0.95    255074
weighted avg       0.95      0.95      0.95    255074



In [ ]:
# Step 7: Train OCSVM on only benign data
X_train = X_scaled[y == 1]  # Train only on normal traffic
model = OneClassSVM(kernel='rbf', gamma='scale', nu=0.025)
model.fit(X_train)

OneClassSVM(nu=0.025)

In [ ]:
# Step 8: Predict on full data (benign + attack)
y_pred = model.predict(X_scaled)

# Step 9: Evaluate performance
print("Confusion Matrix:")
print(confusion_matrix(y, y_pred))

print("\nClassification Report:")
print(classification_report(y, y_pred, target_names=['Attack (-1)', 'Benign (1)']))

In [ ]:
# Train One-Class SVM with RBF kernel with nu=0.05
oc_svm = OneClassSVM(kernel="rbf", gamma="scale", nu=0.025)
oc_svm.fit(intermediate_output[y_train == 1])  # Train only on normal traffic
#oc_svm.fit(X_train[y_train == 1])  # Train only on normal traffic

In [ ]:
# Step 7: Train OCSVM on only benign data
X_train = X_scaled[y == 1]  # Train only on normal traffic
model = OneClassSVM(kernel='sigmoid', gamma='scale', nu=0.1)
model.fit(X_train)
# Step 8: Predict on full data (benign + attack)
y_pred = model.predict(X_scaled)

# Step 9: Evaluate performance
print("Confusion Matrix:")
print(confusion_matrix(y, y_pred))

print("\nClassification Report:")
print(classification_report(y, y_pred, target_names=['Attack (-1)', 'Benign (1)']),digits=4)

In [ ]:
# Step 7: Train OCSVM on only benign data
X_train = X_scaled[y == 1]  # Train only on normal traffic
model = OneClassSVM(kernel='sigmoid', gamma='scale', nu=0.1)
model.fit(X_train)
# Step 8: Predict on full data (benign + attack)
y_pred = model.predict(X_scaled)

# Step 9: Evaluate performance
print("Confusion Matrix:")
print(confusion_matrix(y, y_pred))

print("\nClassification Report:")
print(classification_report(y, y_pred, target_names=['Attack (-1)', 'Benign (1)']),digits=4)


In [ ]:
# Train One-Class SVM with RBF kernel with nu=0.05
oc_svm = OneClassSVM(kernel="rbf", gamma="auto", nu=0.05)
oc_svm.fit(intermediate_output[y_train == 1])  # Train only on normal traffic
#oc_svm.fit(X_train[y_train == 1])  # Train only on normal traffic

OneClassSVM(gamma='auto', nu=0.05)

In [ ]:
y_pred = oc_svm.predict(intermediate_output1)
import numpy as np
from sklearn.metrics import accuracy_score, classification_report
unique_elements = np.unique(y_pred)
print(unique_elements)
y_pred = np.where(y_pred == -1, 0, y_pred)
print(y_pred)
unique_elements = np.unique(y_pred)
print(unique_elements)
# Evaluate performance
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred, digits=4, target_names=["Attack", "Normal"]))

In [ ]:
#...............................End of OC Svm

In [ ]:
##..........................for CNN CODE

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import OneClassSVM
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

# Step 1: Load CIC-IDS2017 dataset
df = pd.read_csv('CIC-IDS2017/Monday-WorkingHours-Normal-network-activities.csv')
df = pd.read_csv('CIC-IDS2017/Friday-WorkingHours-Afternoon-PortScan.csv')
df = pd.read_csv('CIC-IDS2017/Friday-WorkingHours-Morning-Botnet.csv')
df = pd.read_csv('CIC-IDS2017/Friday-WorkingHours-Afternoon 2-DDoS.csv')

In [ ]:
# Optional: Clean column names (strip spaces)
df.columns = df.columns.str.strip()

# Step 2: Separate features and labels
X = df.drop(['Label'], axis=1)
y = df['Label']

In [ ]:
# Step 3: Encode labels: BENIGN -> 1 (normal), Attack -> -1 (anomaly)
y = y.apply(lambda x: 1 if x == 'BENIGN' else 0)

# Step 4: Handle non-numeric columns (if any)
X = X.select_dtypes(include=[np.number])  # Keep only numeric features

In [ ]:
# Step 5.1: Replace inf and -inf with NaN
X.replace([np.inf, -np.inf], np.nan, inplace=True)

# Step 5.2: Fill NaN with 0 or mean (optional: you can also drop rows)
X.fillna(0, inplace=True)

# Step 6: Normalize
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
# Train-test split
import pandas as pd
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25, random_state=42)

In [ ]:
#print(y_train.value_counts())
#print(y_test.value_counts())
import pandas as pd

print(pd.Series(y_train).value_counts())
print(pd.Series(y_test).value_counts())

Label
0    95762
1    95543
Name: count, dtype: int64
Label
1    31994
0    31775
Name: count, dtype: int64


In [ ]:
# Reshape for CNN
X_train = np.expand_dims(X_train, axis=2)
X_test = np.expand_dims(X_test, axis=2)

In [ ]:
# Check data sizes
assert X_train.shape[0] == y_train.shape[0], "Mismatch in X_train and y_train sizes!"
assert X_test.shape[0] == y_test.shape[0], "Mismatch in X_test and y_test sizes!"

In [ ]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout, Input
from tensorflow.keras.regularizers import l2

# Define CNN Model with L2 Regularization
def build_cnn_nsl_kdd(input_shape, dropout=0.5, l2_lambda=0.01):
    inputs = Input(shape=(input_shape, 1))  # Define input shape properly

    x = Conv1D(128, kernel_size=5, activation='relu', padding='same',
               kernel_regularizer=l2(l2_lambda))(inputs)
    x1 = MaxPooling1D(pool_size=2)(x)

    x2 = Conv1D(256, kernel_size=3, activation='relu', padding='same',
                kernel_regularizer=l2(l2_lambda))(x1)
    x3 = MaxPooling1D(pool_size=2)(x2)

    x4 = Conv1D(128, kernel_size=3, activation='relu', padding='same',
                kernel_regularizer=l2(l2_lambda))(x3)

    x5 = Flatten()(x4)

    x6 = Dense(128, activation='relu', kernel_regularizer=l2(l2_lambda))(x5)  # Fixed this line
    x7 = Dropout(dropout)(x6)

    x8 = Dense(32, activation='relu', kernel_regularizer=l2(l2_lambda))(x7)
    x9 = Dropout(dropout)(x8)

    outputs = Dense(1, activation='sigmoid')(x9)

    model = Model(inputs, outputs)
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return model

In [ ]:
# Example usage
input_shape = 78
model = build_cnn_cic_ids_2017(input_shape)
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 78, 1)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d (Conv1D)                 │ (None, 78, 128)        │           768 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ (None, 39, 128)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_1 (Conv1D)               │ (None, 39, 256)        │        98,560 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_1 (MaxPooling1D)  │ (None, 19, 256)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_2 (Conv1D)               │ (None, 19, 128)        │        98,432 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 2432)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │       311,424 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         4,128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 513,345 (1.96 MB)

 Trainable params: 513,345 (1.96 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(191305, 78, 1)
(191305,)
(63769, 78, 1)
(63769,)


In [ ]:
# Define callbacks
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.callbacks import ModelCheckpoint
filepath = "kmean7.keras"
es = EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=20)
mc = ModelCheckpoint(filepath, monitor='val_accuracy', verbose=1, save_best_only=True, mode='max')
callbacks_list = [es, mc]

In [ ]:
# Train model  make epochs =100
history = model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=100, callbacks=callbacks_list, batch_size=128, verbose=2)

Epoch 1/100

Epoch 1: val_accuracy improved from -inf to 0.99363, saving model to kmean7.keras
1495/1495 - 226s - 151ms/step - accuracy: 0.9879 - loss: 0.2687 - val_accuracy: 0.9936 - val_loss: 0.1119
Epoch 2/100

Epoch 2: val_accuracy did not improve from 0.99363
1495/1495 - 258s - 173ms/step - accuracy: 0.9919 - loss: 0.1182 - val_accuracy: 0.9936 - val_loss: 0.1004
Epoch 3/100

Epoch 3: val_accuracy improved from 0.99363 to 0.99393, saving model to kmean7.keras
1495/1495 - 266s - 178ms/step - accuracy: 0.9923 - loss: 0.1080 - val_accuracy: 0.9939 - val_loss: 0.0914
Epoch 4/100

Epoch 4: val_accuracy improved from 0.99393 to 0.99414, saving model to kmean7.keras
1495/1495 - 262s - 175ms/step - accuracy: 0.9924 - loss: 0.1006 - val_accuracy: 0.9941 - val_loss: 0.0844
Epoch 5/100

Epoch 5: val_accuracy improved from 0.99414 to 0.99462, saving model to kmean7.keras
1495/1495 - 267s - 179ms/step - accuracy: 0.9930 - loss: 0.0944 - val_accuracy: 0.9946 - val_loss: 0.0838
Epoch 6/100

Epoc

In [ ]:
# Predict and evaluate
predicted = model.predict(X_test)
predicted = (predicted > 0.5).astype(int)  # Convert probabilities to binary labels
print(classification_report(y_test, predicted,digits=4))

In [ ]:
#Visualize training history
from keras.models import Sequential
from keras.layers import Dense
import matplotlib.pyplot as plt
import numpy

# list all data in history
print(history.history.keys())
# summarize history for accuracy
#plt.plot(history.history['acc'])
plt.plot(history.history['accuracy'])
#plt.plot(history.history['val_acc'])
plt.plot(history.history['val_accuracy'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper right')
plt.show()
# summarize history for loss
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper right')

In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
# Predict and evaluate
predicted = model.predict(X_test)
predicted = (predicted > 0.5).astype(int)  # Convert probabilities to binary labels
print(classification_report(y_test, predicted,digits=4))

In [ ]:
layer_name = 'dense_1'    #write 'dense 1' for your requirement
intermediate_layer_model = Model(inputs=model.input,
                                 outputs=model.get_layer(layer_name).output)
intermediate_output = intermediate_layer_model.predict(X_train)
intermediate_output1=intermediate_layer_model.predict(X_test)
print(intermediate_output.shape)
print(intermediate_output1.shape)

5979/5979 ━━━━━━━━━━━━━━━━━━━━ 82s 14ms/step
1993/1993 ━━━━━━━━━━━━━━━━━━━━ 24s 12ms/step
(191305, 32)
(63769, 32)


In [ ]:
# Serialize model to JSON
model_json = model.to_json()
with open("25n_kmean.json", "w") as json_file:
    json_file.write(model_json)

In [ ]:
# ✅ Save model weights with the correct filename extension
model.save_weights("kmean10.weights.h5")
print("✅ Model weights saved successfully!")

✅ Model weights saved successfully!


In [ ]:
from keras.models import model_from_json

# Load the model architecture
with open("25n_kmean.json", "r") as json_file:
    loaded_model_json = json_file.read()

loaded_model = model_from_json(loaded_model_json)

# Load model weights
loaded_model.load_weights("kmean10.weights.h5")

print("✅ Loaded model from disk!")

✅ Loaded model from disk!


/usr/local/lib/python3.11/dist-packages/keras/src/saving/saving_lib.py:757: UserWarning: Skipping variable loading for optimizer 'adam', because it has 26 variables whereas the saved optimizer has 2 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))


In [ ]:
from sklearn.svm import OneClassSVM

# Train One-Class SVM with linear kernel and nu=0.05
oc_svm = OneClassSVM(kernel="linear", gamma="auto", nu=0.05)
oc_svm.fit(intermediate_output[y_train == 1])  # Train only on normal traffic


In [ ]:
y_pred = oc_svm.predict(intermediate_output1)
import numpy as np
from sklearn.metrics import accuracy_score, classification_report
unique_elements = np.unique(y_pred)
print(unique_elements)
y_pred = np.where(y_pred == -1, 0, y_pred)
print(y_pred)
unique_elements = np.unique(y_pred)
print(unique_elements)
# Evaluate performance
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred, digits=4, target_names=["Attack", "Normal"]))

In [ ]:
# Train One-Class SVM with RBF kernel with nu=0.05
oc_svm = OneClassSVM(kernel="linear", gamma=0.002, nu=0.1)
oc_svm.fit(intermediate_output[y_train == 1])  # Train only on normal traffic
#oc_svm.fit(X_train[y_train == 1])  # Train only on normal traffi

OneClassSVM(gamma=0.002, kernel='linear', nu=0.1)

In [ ]:
y_pred = oc_svm.predict(intermediate_output1)
import numpy as np
from sklearn.metrics import accuracy_score, classification_report
unique_elements = np.unique(y_pred)
print(unique_elements)
y_pred = np.where(y_pred == -1, 0, y_pred)
print(y_pred)
unique_elements = np.unique(y_pred)
print(unique_elements)
# Evaluate performance
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred, digits=4, target_names=["Attack", "Normal"]))

[-1  1]
[0 0 0 ... 1 0 1]
[0 1]
Accuracy: 0.9490818422744594
              precision    recall  f1-score   support

      Attack     0.9076    0.9995    0.9514     31775
      Normal     0.9995    0.8990    0.9466     31994

    accuracy                         0.9491     63769
   macro avg     0.9536    0.9493    0.9490     63769
weighted avg     0.9537    0.9491    0.9490     63769



In [ ]:
y_pred = oc_svm.predict(intermediate_output1)
import numpy as np
from sklearn.metrics import accuracy_score, classification_report
unique_elements = np.unique(y_pred)
print(unique_elements)
y_pred = np.where(y_pred == -1, 0, y_pred)
print(y_pred)
unique_elements = np.unique(y_pred)
print(unique_elements)
# Evaluate performance
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred, digits=4, target_names=["Attack", "Normal"]))

[-1  1]
[0 0 0 ... 1 0 1]
[0 1]
Accuracy: 0.9736862738948392
              precision    recall  f1-score   support

      Attack     0.9506    0.9991    0.9743     31775
      Normal     0.9990    0.9485    0.9731     31994

    accuracy                         0.9737     63769
   macro avg     0.9748    0.9738    0.9737     63769
weighted avg     0.9749    0.9737    0.9737     63769



In [ ]:
# Train One-Class SVM with RBF kernel with nu=0.05
oc_svm = OneClassSVM(kernel="rbf", gamma="scale", nu=0.0125)
oc_svm.fit(intermediate_output[y_train == 1])  # Train only on normal traffic
#oc_svm.fit(X_train[y_train == 1])  # Train only on normal traffic

OneClassSVM(nu=0.0125)

In [ ]:
y_pred = oc_svm.predict(intermediate_output1)
import numpy as np
from sklearn.metrics import accuracy_score, classification_report
unique_elements = np.unique(y_pred)
print(unique_elements)
y_pred = np.where(y_pred == -1, 0, y_pred)
print(y_pred)
unique_elements = np.unique(y_pred)
print(unique_elements)
# Evaluate performance
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred, digits=4, target_names=["Attack", "Normal"]))

[-1  1]
[0 0 0 ... 1 0 1]
[0 1]
Accuracy: 0.9931157772585425
              precision    recall  f1-score   support

      Attack     0.9878    0.9985    0.9931     31775
      Normal     0.9985    0.9877    0.9931     31994

    accuracy                         0.9931     63769
   macro avg     0.9932    0.9931    0.9931     63769
weighted avg     0.9932    0.9931    0.9931     63769



In [ ]:
# Train One-Class SVM with RBF kernel with nu=0.05
oc_svm = OneClassSVM(kernel="rbf", gamma="scale", nu=0.0125)
oc_svm.fit(intermediate_output[y_train == 1])  # Train only on normal traffic
#oc_svm.fit(X_train[y_train == 1])  # Train only on normal traffi

OneClassSVM(nu=0.0125)

In [ ]:
y_pred = oc_svm.predict(intermediate_output1)
import numpy as np
from sklearn.metrics import accuracy_score, classification_report
unique_elements = np.unique(y_pred)
print(unique_elements)
y_pred = np.where(y_pred == -1, 0, y_pred)
print(y_pred)
unique_elements = np.unique(y_pred)
print(unique_elements)
# Evaluate performance
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred, digits=4, target_names=["Attack", "Normal"]))

[-1  1]
[0 0 0 ... 1 0 1]
[0 1]
Accuracy: 0.9929275980492088
              precision    recall  f1-score   support

      Attack     0.9876    0.9983    0.9929     31775
      Normal     0.9983    0.9876    0.9929     31994

    accuracy                         0.9929     63769
   macro avg     0.9930    0.9929    0.9929     63769
weighted avg     0.9930    0.9929    0.9929     63769



In [ ]:
# Train One-Class SVM with RBF kernel with nu=0.05
oc_svm = OneClassSVM(kernel="rbf", gamma="scale", nu=0.05)
oc_svm.fit(intermediate_output[y_train == 1])  # Train only on normal traffic
#oc_svm.fit(X_train[y_train == 1])  # Train only on normal traffi

OneClassSVM(nu=0.05)

In [ ]:
y_pred = oc_svm.predict(intermediate_output1)
import numpy as np
from sklearn.metrics import accuracy_score, classification_report
unique_elements = np.unique(y_pred)
print(unique_elements)
y_pred = np.where(y_pred == -1, 0, y_pred)
print(y_pred)
unique_elements = np.unique(y_pred)
print(unique_elements)
# Evaluate performance
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred, digits=4, target_names=["Attack", "Normal"]))

[-1  1]
[0 0 0 ... 1 0 1]
[0 1]
Accuracy: 0.974517398736063
              precision    recall  f1-score   support

      Attack     0.9520    0.9992    0.9750     31775
      Normal     0.9992    0.9500    0.9740     31994

    accuracy                         0.9745     63769
   macro avg     0.9756    0.9746    0.9745     63769
weighted avg     0.9757    0.9745    0.9745     63769



In [ ]:
# Train One-Class SVM with RBF kernel with nu=0.05
oc_svm = OneClassSVM(kernel="rbf", gamma="auto", nu=0.05)
oc_svm.fit(intermediate_output[y_train == 1])  # Train only on normal traffic
#oc_svm.fit(X_train[y_train == 1])  # Train only on normal traffi

OneClassSVM(gamma='auto', nu=0.05)

In [ ]:
y_pred = oc_svm.predict(intermediate_output1)
import numpy as np
from sklearn.metrics import accuracy_score, classification_report
unique_elements = np.unique(y_pred)
print(unique_elements)
y_pred = np.where(y_pred == -1, 0, y_pred)
print(y_pred)
unique_elements = np.unique(y_pred)
print(unique_elements)
# Evaluate performance
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred, digits=4, target_names=["Attack", "Normal"]))

[-1  1]
[0 0 0 ... 1 0 1]
[0 1]
Accuracy: 0.9745487619376186
              precision    recall  f1-score   support

      Attack     0.9520    0.9993    0.9751     31775
      Normal     0.9992    0.9500    0.9740     31994

    accuracy                         0.9745     63769
   macro avg     0.9756    0.9746    0.9745     63769
weighted avg     0.9757    0.9745    0.9745     63769



In [ ]:
# Train One-Class SVM with RBF kernel with nu=0.05
oc_svm = OneClassSVM(kernel="sigmoid", gamma=0.001, nu=0.1)
oc_svm.fit(intermediate_output[y_train == 1])  # Train only on normal traffic
#oc_svm.fit(X_train[y_train == 1])  # Train only on normal traffi

OneClassSVM(gamma=0.001, kernel='sigmoid', nu=0.1)

In [ ]:
y_pred = oc_svm.predict(intermediate_output1)
import numpy as np
from sklearn.metrics import accuracy_score, classification_report
unique_elements = np.unique(y_pred)
print(unique_elements)
y_pred = np.where(y_pred == -1, 0, y_pred)
print(y_pred)
unique_elements = np.unique(y_pred)
print(unique_elements)
# Evaluate performance
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred, digits=4, target_names=["Attack", "Normal"]))

[-1  1]
[0 0 0 ... 1 0 1]
[0 1]
Accuracy: 0.935768163214101
              precision    recall  f1-score   support

      Attack     0.8860    0.9997    0.9394     31775
      Normal     0.9996    0.8723    0.9316     31994

    accuracy                         0.9358     63769
   macro avg     0.9428    0.9360    0.9355     63769
weighted avg     0.9430    0.9358    0.9355     63769



In [ ]:
# Train One-Class SVM with RBF kernel with nu=0.05
oc_svm = OneClassSVM(kernel="rbf", gamma=0.001, nu=0.2)
oc_svm.fit(intermediate_output[y_train == 1])  # Train only on normal traffic
#oc_svm.fit(X_train[y_train == 1])  # Train only on normal traffi

OneClassSVM(gamma=0.001, nu=0.2)

In [ ]:
y_pred = oc_svm.predict(intermediate_output1)
import numpy as np
from sklearn.metrics import accuracy_score, classification_report
unique_elements = np.unique(y_pred)
print(unique_elements)
y_pred = np.where(y_pred == -1, 0, y_pred)
print(y_pred)
unique_elements = np.unique(y_pred)
print(unique_elements)
# Evaluate performance
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred, digits=4, target_names=["Attack", "Normal"]))

[-1  1]
[0 0 0 ... 1 0 1]
[0 1]
Accuracy: 0.8992927598049208
              precision    recall  f1-score   support

      Attack     0.8320    0.9997    0.9082     31775
      Normal     0.9996    0.7996    0.8885     31994

    accuracy                         0.8993     63769
   macro avg     0.9158    0.8996    0.8983     63769
weighted avg     0.9161    0.8993    0.8983     63769



In [ ]:
# Train One-Class SVM with RBF kernel with nu=0.05
oc_svm = OneClassSVM(kernel="rbf", gamma=0.001, nu=0.1)
oc_svm.fit(intermediate_output[y_train == 1])  # Train only on normal traffic
#oc_svm.fit(X_train[y_train == 1])  # Train only on normal traffi

OneClassSVM(gamma=0.001, nu=0.1)

In [ ]:
y_pred = oc_svm.predict(intermediate_output1)
import numpy as np
from sklearn.metrics import accuracy_score, classification_report
unique_elements = np.unique(y_pred)
print(unique_elements)
y_pred = np.where(y_pred == -1, 0, y_pred)
print(y_pred)
unique_elements = np.unique(y_pred)
print(unique_elements)
# Evaluate performance
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred, digits=4, target_names=["Attack", "Normal"]))

[-1  1]
[0 0 0 ... 1 0 1]
[0 1]
Accuracy: 0.9503677335382396
              precision    recall  f1-score   support

      Attack     0.9098    0.9994    0.9525     31775
      Normal     0.9994    0.9016    0.9480     31994

    accuracy                         0.9504     63769
   macro avg     0.9546    0.9505    0.9503     63769
weighted avg     0.9548    0.9504    0.9503     63769



In [ ]:
# Train One-Class SVM with RBF kernel with nu=0.05
oc_svm = OneClassSVM(kernel="rbf", gamma="scale", nu=0.075)
oc_svm.fit(intermediate_output[y_train == 1])  # Train only on normal traffic
#oc_svm.fit(X_train[y_train == 1])  # Train only on normal traffic

OneClassSVM(nu=0.075)

In [ ]:
y_pred = oc_svm.predict(intermediate_output1)
import numpy as np
from sklearn.metrics import accuracy_score, classification_report
unique_elements = np.unique(y_pred)
print(unique_elements)
y_pred = np.where(y_pred == -1, 0, y_pred)
print(y_pred)
unique_elements = np.unique(y_pred)
print(unique_elements)
# Evaluate performance
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred, digits=4, target_names=["Attack", "Normal"]))

[-1  1]
[0 0 0 ... 1 0 1]
[0 1]
Accuracy: 0.9624582477379291
              precision    recall  f1-score   support

      Attack     0.9305    0.9993    0.9637     31775
      Normal     0.9992    0.9259    0.9612     31994

    accuracy                         0.9625     63769
   macro avg     0.9649    0.9626    0.9624     63769
weighted avg     0.9650    0.9625    0.9624     63769



In [ ]:
# Train One-Class SVM with RBF kernel with nu=0.05
oc_svm = OneClassSVM(kernel="rbf", gamma="auto", nu=0.05)
oc_svm.fit(intermediate_output[y_train == 1])  # Train only on normal traffic
#oc_svm.fit(X_train[y_train == 1])  # Train only on normal traffic

OneClassSVM(gamma='auto', nu=0.05)

In [ ]:
y_pred = oc_svm.predict(intermediate_output1)
import numpy as np
from sklearn.metrics import accuracy_score, classification_report
unique_elements = np.unique(y_pred)
print(unique_elements)
y_pred = np.where(y_pred == -1, 0, y_pred)
print(y_pred)
unique_elements = np.unique(y_pred)
print(unique_elements)
# Evaluate performance
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred, digits=4, target_names=["Attack", "Normal"]))

[-1  1]
[0 0 0 ... 1 0 1]
[0 1]
Accuracy: 0.9745487619376186
              precision    recall  f1-score   support

      Attack     0.9520    0.9993    0.9751     31775
      Normal     0.9992    0.9500    0.9740     31994

    accuracy                         0.9745     63769
   macro avg     0.9756    0.9746    0.9745     63769
weighted avg     0.9757    0.9745    0.9745     63769



In [ ]:
# Train One-Class SVM with RBF kernel with nu=0.05
oc_svm = OneClassSVM(kernel="rbf", gamma="scale", nu=0.025)
oc_svm.fit(intermediate_output[y_train == 1])  # Train only on normal traffic
#oc_svm.fit(X_train[y_train == 1])  # Train only on normal traffic

OneClassSVM(nu=0.025)

In [ ]:
y_pred = oc_svm.predict(intermediate_output1)
import numpy as np
from sklearn.metrics import accuracy_score, classification_report
unique_elements = np.unique(y_pred)
print(unique_elements)
y_pred = np.where(y_pred == -1, 0, y_pred)
print(y_pred)
unique_elements = np.unique(y_pred)
print(unique_elements)
# Evaluate performance
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred, digits=4, target_names=["Attack", "Normal"]))

[-1  1]
[0 0 0 ... 1 0 1]
[0 1]
Accuracy: 0.985588608885195
              precision    recall  f1-score   support

      Attack     0.9732    0.9986    0.9857     31775
      Normal     0.9986    0.9727    0.9854     31994

    accuracy                         0.9856     63769
   macro avg     0.9859    0.9856    0.9856     63769
weighted avg     0.9859    0.9856    0.9856     63769



In [ ]:
# Train One-Class SVM with RBF kernel with nu=0.05
oc_svm = OneClassSVM(kernel="rbf", gamma="auto", nu=0.05)
oc_svm.fit(intermediate_output[y_train == 1])  # Train only on normal traffic
#oc_svm.fit(X_train[y_train == 1])  # Train only on normal traffic

OneClassSVM(gamma='auto', nu=0.05)

In [ ]:
from sklearn.metrics import accuracy_score, classification_report
import numpy as np

# Predict using Isolation Forest
y_pred_if = iso_forest.predict(intermediate_output1)
unique_elements = np.unique(y_pred)
print(unique_elements)
y_pred = np.where(y_pred == -1, 0, y_pred)
print(y_pred)
unique_elements = np.unique(y_pred)
print(unique_elements)
# Evaluate performance
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred, digits=4, target_names=["Attack", "Normal"]))

[0 1]
[0 0 0 ... 1 0 1]
[0 1]
Accuracy: 0.9929275980492088
              precision    recall  f1-score   support

      Attack     0.9876    0.9983    0.9929     31775
      Normal     0.9983    0.9876    0.9929     31994

    accuracy                         0.9929     63769
   macro avg     0.9930    0.9929    0.9929     63769
weighted avg     0.9930    0.9929    0.9929     63769



In [ ]:
y_pred = oc_svm.predict(intermediate_output1)
import numpy as np
from sklearn.metrics import accuracy_score, classification_report
unique_elements = np.unique(y_pred)
print(unique_elements)
y_pred = np.where(y_pred == -1, 0, y_pred)
print(y_pred)
unique_elements = np.unique(y_pred)
print(unique_elements)
# Evaluate performance
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred, digits=4, target_names=["Attack", "Normal"]))

[-1  1]
[0 0 0 ... 1 0 1]
[0 1]
Accuracy: 0.9744233091313962
              precision    recall  f1-score   support

      Attack     0.9520    0.9991    0.9750     31775
      Normal     0.9990    0.9499    0.9739     31994

    accuracy                         0.9744     63769
   macro avg     0.9755    0.9745    0.9744     63769
weighted avg     0.9756    0.9744    0.9744     63769



In [ ]:
---------------#isolation forest#--------------------

In [ ]:
from sklearn.ensemble import IsolationForest

# Train Isolation Forest on normal traffic only (label == 1)
iso_forest = IsolationForest(n_estimators=100, contamination=0.1, random_state=42)
iso_forest.fit(intermediate_output[y_train == 1])  # Train on normal class only
# iso_forest.fit(X_train[y_train == 1])  # Alternative if not using intermediate features

IsolationForest(contamination=0.1, random_state=42)

In [ ]:
from sklearn.metrics import accuracy_score, classification_report
import numpy as np

# Predict using Isolation Forest
y_pred_if = iso_forest.predict(intermediate_output1)

# Check unique predicted labels
unique_elements = np.unique(y_pred_if)
print("Raw Predictions:", unique_elements)

# Convert Isolation Forest output: -1 (anomaly → 0), 1 (normal → 1)
y_pred_if = np.where(y_pred_if == -1, 0, y_pred_if)
print("Mapped Predictions:", y_pred_if)
print("Unique Labels After Mapping:", np.unique(y_pred_if))

# Evaluate performance
print("Accuracy:", accuracy_score(y_test, y_pred_if))
print(classification_report(y_test, y_pred_if, digits=4, target_names=["Attack", "Normal"]))

In [ ]:
from sklearn.ensemble import IsolationForest

# Train Isolation Forest on normal traffic only (label == 1)
iso_forest = IsolationForest(n_estimators=100, contamination=0.1, random_state=42)
iso_forest.fit(intermediate_output[y_train == 1])  # Train on normal class only
# iso_forest.fit(X_train[y_train == 1])  # Alternative if not using intermediate features

In [ ]:
from sklearn.metrics import accuracy_score, classification_report
import numpy as np

# Predict using Isolation Forest
y_pred_if = iso_forest.predict(intermediate_output1)

# Check unique predicted labels
unique_elements = np.unique(y_pred_if)
print("Raw Predictions:", unique_elements)

# Convert Isolation Forest output: -1 (anomaly → 0), 1 (normal → 1)
y_pred_if = np.where(y_pred_if == -1, 0, y_pred_if)
print("Mapped Predictions:", y_pred_if)
print("Unique Labels After Mapping:", np.unique(y_pred_if))

# Evaluate performance
print("Accuracy:", accuracy_score(y_test, y_pred_if))
print(classification_report(y_test, y_pred_if, digits=4, target_names=["Attack", "Normal"]))

Raw Predictions: [-1  1]
Mapped Predictions: [0 0 0 ... 1 0 1]
Unique Labels After Mapping: [0 1]
Accuracy: 0.9499913751195722
              precision    recall  f1-score   support

      Attack     0.9092    0.9994    0.9522     31775
      Normal     0.9994    0.9009    0.9476     31994

    accuracy                         0.9500     63769
   macro avg     0.9543    0.9502    0.9499     63769
weighted avg     0.9544    0.9500    0.9499     63769



In [ ]:
from sklearn.ensemble import IsolationForest

# Train Isolation Forest on normal traffic only (label == 1)
iso_forest = IsolationForest(n_estimators=100, contamination=0.01, max_samples=0.5, max_features=0.7,random_state=42)
iso_forest.fit(intermediate_output[y_train == 1])  # Train on normal class only
# iso_forest.fit(X_train[y_train == 1])  # Alternative if not using intermediate features

IsolationForest(contamination=0.01, max_features=0.7, max_samples=0.5,
                random_state=42)

In [ ]:
from sklearn.metrics import accuracy_score, classification_report
import numpy as np

# Predict using Isolation Forest
y_pred_if = iso_forest.predict(intermediate_output1)

# Check unique predicted labels
unique_elements = np.unique(y_pred_if)
print("Raw Predictions:", unique_elements)

# Convert Isolation Forest output: -1 (anomaly → 0), 1 (normal → 1)
y_pred_if = np.where(y_pred_if == -1, 0, y_pred_if)
print("Mapped Predictions:", y_pred_if)
print("Unique Labels After Mapping:", np.unique(y_pred_if))

# Evaluate performance
print("Accuracy:", accuracy_score(y_test, y_pred_if))
print(classification_report(y_test, y_pred_if, digits=4, target_names=["Attack", "Normal"]))

Raw Predictions: [-1  1]
Mapped Predictions: [0 0 0 ... 1 0 1]
Unique Labels After Mapping: [0 1]
Accuracy: 0.9946996189371011
              precision    recall  f1-score   support

      Attack     0.9905    0.9990    0.9947     31775
      Normal     0.9990    0.9904    0.9947     31994

    accuracy                         0.9947     63769
   macro avg     0.9947    0.9947    0.9947     63769
weighted avg     0.9947    0.9947    0.9947     63769



In [ ]:
from sklearn.ensemble import IsolationForest

# Train Isolation Forest on normal traffic only (label == 1)
iso_forest = IsolationForest(n_estimators=100, contamination=0.05, max_samples=0.5, max_features=0.7,random_state=42)
iso_forest.fit(intermediate_output[y_train == 1])  # Train on normal class only
# iso_forest.fit(X_train[y_train == 1])  # Alternative if not using intermediate features

IsolationForest(contamination=0.05, max_features=0.7, max_samples=0.5,
                random_state=42)

In [ ]:
from sklearn.metrics import accuracy_score, classification_report
import numpy as np

# Predict using Isolation Forest
y_pred_if = iso_forest.predict(intermediate_output1)

# Check unique predicted labels
unique_elements = np.unique(y_pred_if)
print("Raw Predictions:", unique_elements)

# Convert Isolation Forest output: -1 (anomaly → 0), 1 (normal → 1)
y_pred_if = np.where(y_pred_if == -1, 0, y_pred_if)
print("Mapped Predictions:", y_pred_if)
print("Unique Labels After Mapping:", np.unique(y_pred_if))

# Evaluate performance
print("Accuracy:", accuracy_score(y_test, y_pred_if))
print(classification_report(y_test, y_pred_if, digits=4, target_names=["Attack", "Normal"]))

Raw Predictions: [-1  1]
Mapped Predictions: [0 0 0 ... 1 0 1]
Unique Labels After Mapping: [0 1]
Accuracy: 0.9747369411469523
              precision    recall  f1-score   support

      Attack     0.9524    0.9992    0.9753     31775
      Normal     0.9992    0.9504    0.9742     31994

    accuracy                         0.9747     63769
   macro avg     0.9758    0.9748    0.9747     63769
weighted avg     0.9759    0.9747    0.9747     63769



In [ ]:
from sklearn.metrics import accuracy_score, classification_report
import numpy as np
# Predict using Isolation Forest
y_pred_if = iso_forest.predict(intermediate_output1)
unique_elements = np.unique(y_pred)
print(unique_elements)
y_pred = np.where(y_pred == -1, 0, y_pred)
print(y_pred)
unique_elements = np.unique(y_pred)
print(unique_elements)
# Evaluate performance
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred, digits=4, target_names=["Attack", "Normal"]))

[0 1]
[0 0 0 ... 1 0 1]
[0 1]
Accuracy: 0.9929275980492088
              precision    recall  f1-score   support

      Attack     0.9876    0.9983    0.9929     31775
      Normal     0.9983    0.9876    0.9929     31994

    accuracy                         0.9929     63769
   macro avg     0.9930    0.9929    0.9929     63769
weighted avg     0.9930    0.9929    0.9929     63769



In [ ]:
# Train Isolation Forest on normal traffic only (label == 1)
iso_forest = IsolationForest(n_estimators=100, contamination=0.1, random_state=42)
iso_forest.fit(intermediate_output[y_train == 1])  # Train on normal class only
# iso_forest.fit(X_train[y_train == 1])  # Alternative if not using intermediate features